version: '3'
services:
  scrapper:
    build: scrapper
    image: bookfinder/scrapper:latest
    deploy:
      replicas: 2
    environment:
    - SPRING_PROFILES_ACTIVE=${ACTIVE_SCRAPPER_PROFILE}
  db:
    build: db
    image: bookfinder/db:latest
    environment:
    - POSTGRES_USER=user
    - POSTGRES_DB=
    - POSTGRES_DB=scrapper
  gateway:
    build: gateway
    image: bookfinder/gateway:latest
    ports:
    - "${GATEWAY_PORT}:8765"
  discovery:
    build: discovery
    image: bookfinder/discovery:latest
    environment:
    - SERVER_PORT=${EUREKA_PORT}
    ports:
    - "${EUREKA_PORT}:8761"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181