version: '3'
services:
  scrapper:
    build: scrapper
    image: bookfinder/scrapper:latest
    deploy:
      replicas: 2
    ports:
      - "${SCRAPPER_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_SCRAPPER_PROFILE}
  db:
    build: db
    image: bookfinder/db:latest
    environment:
      - POSTGRES_DB=scrapper
    ports:
      - "5432:5432"