spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
zuul:
  routes:
    scrapper:
      path: /books/**
      stripPrefix: false
  ignoredServices: '*'
server:
  port: 8765