eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
    register-with-eureka: false
zuul:
  routes:
    scrapper:
      path: /books/**
      stripPrefix: false
  ignoredServices: '*'
server:
  port: 8765